openapi: 3.0.0
info:
  title: Sample API with External Reference
  version: 1.0.0

paths:
  /users/{userId}:
    get:
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/yashasvi13/openapi-spec/main/schemas/user.yaml#/components/schemas/User"
